version: '3'

services:

  zammad-backup:
    volumes:
      - ./msl/data/zammad-backup:/var/tmp/zammad
      - postgresql-data:/var/lib/postgresql/data:ro

  zammad-postgresql:
    volumes:
      - ./msl/data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  zammad-elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 768MiB
        reservations:
          memory: 512MiB

  zammad-nginx:
    ports:
      - "8088:8080"
