version: '3'

volumes:
  traefik:

services:

  zammad-backup:
    volumes:
      - ./msl/data/zammad-backup:/var/tmp/zammad
      - postgresql-data:/var/lib/postgresql/data:ro

  zammad-postgresql:
    volumes:
      - ./msl/data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  zammad-elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    deploy:
      resources:
        limits:
          memory: 768MiB
        reservations:
          memory: 512MiB

  zammad-nginx:
    # ports:
    #   - "8088:8080"
    labels:
      - traefik.enable=true
      - traefik.http.routers.zammad.rule=Host(`support.msl.solutions`)
      - traefik.http.routers.zammad.entrypoints=websecure
      - traefik.http.routers.zammad.tls.certresolver=letsencrypt
      - traefik.http.routers.zammad.service=zammad
      - traefik.http.services.zammad.loadbalancer.server.port=8080
    environment:
      - RAILS_TRUSTED_PROXIES=['127.0.0.1', '::1', 'traefik']
      - NGINX_SERVER_SCHEME=https

  traefik:
    image: traefik:v2.11
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --log.level=DEBUG
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.address=:80
      - --certificatesresolvers.letsencrypt.acme.email=florian@msl.solutions
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnsChallenge.provider=manual
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik:/letsencrypt
    restart:
      unless-stopped
